/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

import Clases.Revistas;
import Clases.SerializarRevistas;
import java.io.File;
import java.io.IOException;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class AltaRevistas extends javax.swing.JFrame {
      public String path;
      public String auxPath;
      public Revistas magazine= null;
      public static ArrayList<Revistas> auxRevistas = new ArrayList<Revistas>();
      public ListIterator li;
      public int fuera;
       /** los comentarios al codigo de este JFrame, son los mismos (salvando 
        * algunas variables, de lo que se puede ver en el JFrame "AltaLibros.Java" 
        */
    /**
     * Creates new form AltaRevistas
     */
    public AltaRevistas() {
        initComponents();
        this.setTitle("Biblioteca de la UAH");
        
    }
     public GregorianCalendar getFechaPublicacion() {
        Date dia = (Date) fechaPublicacion.getValue();
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dia);
        return gc;
    }
    public GregorianCalendar getFechaDisponible() {
        Date dia = (Date) anioDisponible.getValue();
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dia);
        return gc;
 }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        autores = new javax.swing.JTextField();
        paginas = new javax.swing.JTextField();
        materia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        periocidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        volumen = new javax.swing.JTextField();
        numeroRevista = new javax.swing.JTextField();
        ubicacion = new javax.swing.JTextField();
        coleccion = new javax.swing.JComboBox();
        introducirRevista = new javax.swing.JButton();
        reiniciarDatos = new javax.swing.JButton();
        fechaPublicacion = new javax.swing.JSpinner();
        anioDisponible = new javax.swing.JSpinner();
        cargarImagen = new javax.swing.JButton();
        imagenCaratula = new javax.swing.JLabel();
        GenerarISBN = new javax.swing.JButton();
        GenerarCodigo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionAtras = new javax.swing.JMenu();
        IrAltaPublicaciones = new javax.swing.JRadioButtonMenuItem();
        IrGestionSocios = new javax.swing.JRadioButtonMenuItem();
        IrMenuPrincipal = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBiblio.png"))); // NOI18N

        jLabel1.setText("código");

        jLabel2.setText("ISBN");

        jLabel3.setText("Título");

        jLabel4.setText("Autores");

        jLabel6.setText("Fecha de Publicación");

        jLabel7.setText("Páginas");

        jLabel8.setText("con Colección");

        jLabel15.setText("Caráctula");

        jLabel9.setText("Materia");

        jLabel10.setText("Observaciones");

        codigo.setEditable(false);

        ISBN.setEditable(false);

        autores.setToolTipText("Separa los autores con \",\"");

        observaciones.setColumns(20);
        observaciones.setRows(5);
        observaciones.setText("\n");
        jScrollPane1.setViewportView(observaciones);

        jLabel11.setText("Periocidad");

        jLabel12.setText("Volumen");

        jLabel13.setText("Numero");

        jLabel14.setText("Año Disponible");

        jLabel16.setText("Ubicación en la Biblioteca");

        ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionActionPerformed(evt);
            }
        });

        coleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));

        introducirRevista.setBackground(new java.awt.Color(51, 255, 51));
        introducirRevista.setText("INTRODUCIR REVISTA");
        introducirRevista.setToolTipText("Introduce una revista en la Biblioteca, debe rellenar todos los campos");
        introducirRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirRevistaActionPerformed(evt);
            }
        });

        reiniciarDatos.setBackground(new java.awt.Color(255, 51, 51));
        reiniciarDatos.setText("REINICIAR DATOS");
        reiniciarDatos.setToolTipText("Reinicia todos los campos");
        reiniciarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarDatosActionPerformed(evt);
            }
        });

        fechaPublicacion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-11676099600000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        fechaPublicacion.setToolTipText("haz \"doble click\" en el dato de la fecha que quieras cambiar");
        fechaPublicacion.setEditor(new javax.swing.JSpinner.DateEditor(fechaPublicacion, "dd/MM/yyyy"));

        anioDisponible.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-11676099600000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        anioDisponible.setToolTipText("haz \"doble click\" en el dato de la fecha que quieras cambiar");
        anioDisponible.setEditor(new javax.swing.JSpinner.DateEditor(anioDisponible, "dd/MM/yyyy"));

        cargarImagen.setText("Cargar imagen");
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });

        GenerarISBN.setBackground(new java.awt.Color(51, 204, 255));
        GenerarISBN.setText("Generar");
        GenerarISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarISBNActionPerformed(evt);
            }
        });

        GenerarCodigo.setBackground(new java.awt.Color(51, 204, 255));
        GenerarCodigo.setText("Generar");
        GenerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarCodigoActionPerformed(evt);
            }
        });

        opcionAtras.setText("ATRAS");

        IrAltaPublicaciones.setSelected(true);
        IrAltaPublicaciones.setText("Alta de Publicaciones");
        IrAltaPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrAltaPublicacionesActionPerformed(evt);
            }
        });
        opcionAtras.add(IrAltaPublicaciones);

        IrGestionSocios.setSelected(true);
        IrGestionSocios.setText("Gestion Publicaciones");
        IrGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrGestionSociosActionPerformed(evt);
            }
        });
        opcionAtras.add(IrGestionSocios);

        IrMenuPrincipal.setSelected(true);
        IrMenuPrincipal.setText("Menu Principal");
        IrMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuPrincipalActionPerformed(evt);
            }
        });
        opcionAtras.add(IrMenuPrincipal);

        jMenuBar1.add(opcionAtras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubicacion)
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(GenerarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(37, 37, 37)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(37, 37, 37)
                                                        .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(37, 37, 37)
                                                        .addComponent(GenerarISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(16, 16, 16))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(periocidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(anioDisponible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numeroRevista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addComponent(volumen, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reiniciarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(introducirRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagenCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cargarImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenerarCodigo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenerarISBN))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(periocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(numeroRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(introducirRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reiniciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(anioDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IrGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrGestionSociosActionPerformed
        // TODO add your handling code here:
        GestionAplicaciones ges1 = new GestionAplicaciones();
        ges1.setVisible(true);
        SerializarRevistas.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrGestionSociosActionPerformed

    private void IrMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuPrincipalActionPerformed
        // TODO add your handling code here:
        Biblioteca library = new Biblioteca();
        library.setVisible(true);
        SerializarRevistas.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrMenuPrincipalActionPerformed

    private void IrAltaPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrAltaPublicacionesActionPerformed
        // TODO add your handling code here:
        AltaPublicaciones altaP=new AltaPublicaciones();
        altaP.setVisible(true);
        SerializarRevistas.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrAltaPublicacionesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
        SerializarRevistas.cargarDatos();
        
    }//GEN-LAST:event_formWindowOpened

    private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionActionPerformed

    private void reiniciarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarDatosActionPerformed
         // Pone en blanco todos los campos de texto. Ademas  pone en su estado inicial al spinner de la fecha y al combobox
        codigo.setText("");
        ISBN.setText("");
        titulo.setText("");
        autores.setText("");
        paginas.setText("");
        materia.setText("");
        observaciones.setText("");
        periocidad.setText("");
        volumen.setText("");
        numeroRevista.setText("");
        ubicacion.setText("");
        GregorianCalendar gc = new GregorianCalendar();
        gc=(GregorianCalendar) Calendar.getInstance();
        Date dia = gc.getTime();
        fechaPublicacion.setValue(dia);
        anioDisponible.setValue(dia);
        imagenCaratula.setIcon(null);
        coleccion.setSelectedIndex(0);
    }//GEN-LAST:event_reiniciarDatosActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // TODO add your handling code here:
        String aux="C:\\Users\\Alvaro\\Documents\\NetBeansProjects\\PracticaFinal\\";
        //cadena que sirve para hacer la diferencia entre imagenes del proyecto y imagenes fuera de la carpeta
        String aux2;
        int ultimo;
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            path = file.getAbsolutePath();
            ultimo=path.length();
            if (ultimo>56){
                aux2=path.substring(0, 57);
                if (aux2.equals(aux)){
                     auxPath=path.substring(57,ultimo);
                     ImageIcon imagenes= new ImageIcon(auxPath);
                     imagenCaratula.setIcon(imagenes);
                     fuera=1;
                }
            }
            else{
                ImageIcon imagenes= new ImageIcon(path);
                imagenCaratula.setIcon(imagenes);
                fuera=0;
            }
                
              
        } else {
            fc.setEnabled(false);
        }
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void introducirRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirRevistaActionPerformed
        // TODO add your handling code here:
        String imagenC; 
        try{
            String CodigoControl= codigo.getText();
            String isbn= ISBN.getText();
            String title= titulo.getText();
            String pag=paginas.getText();
            int pagi= Integer.parseInt(pag);//se pasa de un String a un int
            String mater= materia.getText();
            String collection= (String) coleccion.getSelectedItem();
            String obser= observaciones.getText();
            String period= periocidad.getText();
            String vol= volumen.getText();
            int volR=Integer.parseInt(vol);
            String num= numeroRevista.getText();
            int number=Integer.parseInt(num);
            String fisica= ubicacion.getText();
            String author= autores.getText();
        
            if (fuera==1){
                 imagenC=auxPath;   
            }
            else {
                 imagenC=path;
            }
        
            GregorianCalendar fechaPubli=getFechaPublicacion();
            GregorianCalendar fechaDisponible=getFechaDisponible();
            if (path.equals("") && auxPath.equals("")){
                
            } else {
                magazine =new Revistas(period,volR,number,fechaDisponible,fisica,CodigoControl,isbn,title,author,fechaPubli,imagenC,pagi,collection,mater,obser);
                boolean alta=SerializarRevistas.altaRevista(magazine);
                if (alta==true) {
                    JOptionPane.showMessageDialog(this, "Revista dada de alta.", "Mensaje de Alta", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);               
                }
           }   
     }catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Campos sin rellenar o formato equivocado", "Mensaje de error", JOptionPane.ERROR_MESSAGE);   
        JOptionPane.showMessageDialog(this,"Si no ha insertado ninguna imagen, por favor insertela;"
                    + "\n"+ "Si no tiene ninguna imagen a  insertar puede usar una"
                    + " estandar que tiene la carpeta del programa" + "\n"
                    +"(la imagen se llama 'NoCaratula.PNG')"
                    ,"Mensaje de error",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_introducirRevistaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        SerializarRevistas.guardarDatos();
    }//GEN-LAST:event_formWindowClosing

    private void GenerarISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarISBNActionPerformed
        // TODO add your handling code here:
        int codigoPubli;
        String auxcodi;
        String codigoLib = null;
        Random rand = new Random();
        
        auxRevistas = SerializarRevistas.getRevista();
        li = auxRevistas.listIterator();
        codigoPubli = rand.nextInt(10000);
        codigoPubli = codigoPubli + 1000000;
        codigoLib = Integer.toString(codigoPubli);
        ISBN.setText(codigoLib);

        if (auxRevistas.size() >= 0) {
            while (li.hasNext()) {
                magazine = (Revistas) li.next();
                if (magazine != null) {
                    auxcodi = magazine.getCodigoControl();
                    if (auxcodi.equals(codigoLib)) {
                        codigoPubli = rand.nextInt(10000);
                        codigoPubli = codigoPubli + 1000000;
                        codigoLib = Integer.toString(codigoPubli);
                        ISBN.setText(codigoLib);
                    }
                }
            }
        }



    }//GEN-LAST:event_GenerarISBNActionPerformed

    private void GenerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarCodigoActionPerformed
        // TODO add your handling code here:
        int codigoPubli;
        String auxcodi;
        String codigoLib = null;
        Random rand = new Random();
       
        auxRevistas = SerializarRevistas.getRevista();
        li = auxRevistas.listIterator();
        codigoPubli = rand.nextInt(10000);
        codigoPubli = codigoPubli + 1000000;
        codigoLib = Integer.toString(codigoPubli);
        codigo.setText(codigoLib);

        if (auxRevistas.size() >= 0) {
            while (li.hasNext()) {
                magazine = (Revistas) li.next();
                if (magazine != null) {
                    auxcodi = magazine.getCodigoControl();
                    if (auxcodi.equals(codigoLib)) {
                        codigoPubli = rand.nextInt(10000);
                        codigoPubli = codigoPubli + 1000000;
                        codigoLib = Integer.toString(codigoPubli);
                        codigo.setText(codigoLib);
                    }
                }
            }
        }
    }//GEN-LAST:event_GenerarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AltaRevistas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarCodigo;
    private javax.swing.JButton GenerarISBN;
    private javax.swing.JTextField ISBN;
    private javax.swing.JRadioButtonMenuItem IrAltaPublicaciones;
    private javax.swing.JRadioButtonMenuItem IrGestionSocios;
    private javax.swing.JRadioButtonMenuItem IrMenuPrincipal;
    private javax.swing.JSpinner anioDisponible;
    private javax.swing.JTextField autores;
    private javax.swing.JButton cargarImagen;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox coleccion;
    private javax.swing.JSpinner fechaPublicacion;
    private javax.swing.JLabel imagenCaratula;
    private javax.swing.JButton introducirRevista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materia;
    private javax.swing.JTextField numeroRevista;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JMenu opcionAtras;
    private javax.swing.JTextField paginas;
    private javax.swing.JTextField periocidad;
    private javax.swing.JButton reiniciarDatos;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField ubicacion;
    private javax.swing.JTextField volumen;
    // End of variables declaration//GEN-END:variables
}
