/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

import Clases.Libros;
import Clases.SerializarLibros;
import java.awt.HeadlessException;
import java.io.File;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class AltaLibros extends javax.swing.JFrame {
      public String path,auxPath;
      public Libros book= null;
      int contadorCodigo;
      public static ArrayList<Libros> auxlibros = new ArrayList<Libros>();
      public ListIterator li;
      public int fuera;
      public boolean seguir=false;
      
    /**
     * Creates new form AltaLibros
     */
    public AltaLibros() {
        initComponents();
        this.setTitle("Biblioteca de la UAH");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        autores = new javax.swing.JTextField();
        paginas = new javax.swing.JTextField();
        materia = new javax.swing.JTextField();
        editorial = new javax.swing.JTextField();
        edicion = new javax.swing.JTextField();
        localidad = new javax.swing.JTextField();
        ubicacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        coleccion = new javax.swing.JComboBox();
        introducirLibro = new javax.swing.JButton();
        reiniciarDatos = new javax.swing.JButton();
        fechaPublicacion = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        cargarImagen = new javax.swing.JButton();
        imagenCaratula = new javax.swing.JLabel();
        GenerarCodigo = new javax.swing.JButton();
        GenerarISBN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionAtras = new javax.swing.JMenu();
        IrAltaPublicaciones = new javax.swing.JRadioButtonMenuItem();
        IrGestionSocios = new javax.swing.JRadioButtonMenuItem();
        IrMenuPrincipal = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBiblio.png"))); // NOI18N

        jLabel1.setText("código");

        jLabel2.setText("ISBN");

        jLabel3.setText("Título");

        jLabel4.setText("Autores");

        jLabel6.setText("Fecha de Publicación");

        jLabel7.setText("Páginas");

        jLabel8.setText("con Colección");

        jLabel9.setText("Materia");

        jLabel10.setText("Observaciones");

        jLabel11.setText("Editorial");

        jLabel12.setText("Localidad");

        jLabel13.setText("Edición");

        jLabel14.setText("Ubicación en la Biblioteca");
        jLabel14.setRequestFocusEnabled(false);

        jLabel16.setText("Resumen");

        codigo.setEditable(false);

        ISBN.setEditable(false);

        autores.setToolTipText("Separar los autores entre \",\"");
        autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoresActionPerformed(evt);
            }
        });

        materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaActionPerformed(evt);
            }
        });

        resumen.setColumns(20);
        resumen.setRows(5);
        jScrollPane1.setViewportView(resumen);

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane2.setViewportView(observaciones);

        coleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));

        introducirLibro.setBackground(new java.awt.Color(51, 255, 51));
        introducirLibro.setText("INTRODUCIR LIBRO");
        introducirLibro.setToolTipText("Introduce en la Biblioteca un nuevo libro, deben estar todos los campos rellenos");
        introducirLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirLibroActionPerformed(evt);
            }
        });

        reiniciarDatos.setBackground(new java.awt.Color(255, 51, 51));
        reiniciarDatos.setText("REINICIAR DATOS");
        reiniciarDatos.setToolTipText("reinicia los datos de los campos");
        reiniciarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarDatosActionPerformed(evt);
            }
        });

        fechaPublicacion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-11676099600000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        fechaPublicacion.setToolTipText("haz \"doble click\" en el dato de la fecha que quieras cambiar");
        fechaPublicacion.setEditor(new javax.swing.JSpinner.DateEditor(fechaPublicacion, "dd/MM/yyyy"));

        jLabel17.setText("Carátula");

        cargarImagen.setText("Cargar imagen");
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });

        GenerarCodigo.setBackground(new java.awt.Color(51, 204, 255));
        GenerarCodigo.setText("Generar");
        GenerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarCodigoActionPerformed(evt);
            }
        });

        GenerarISBN.setBackground(new java.awt.Color(51, 204, 255));
        GenerarISBN.setText("Generar");
        GenerarISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarISBNActionPerformed(evt);
            }
        });

        opcionAtras.setText("ATRAS");

        IrAltaPublicaciones.setSelected(true);
        IrAltaPublicaciones.setText("Alta de Publicaciones");
        IrAltaPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrAltaPublicacionesActionPerformed(evt);
            }
        });
        opcionAtras.add(IrAltaPublicaciones);

        IrGestionSocios.setSelected(true);
        IrGestionSocios.setText("Gestion Publicaciones");
        IrGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrGestionSociosActionPerformed(evt);
            }
        });
        opcionAtras.add(IrGestionSocios);

        IrMenuPrincipal.setSelected(true);
        IrMenuPrincipal.setText("Menu Principal");
        IrMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuPrincipalActionPerformed(evt);
            }
        });
        opcionAtras.add(IrMenuPrincipal);

        jMenuBar1.add(opcionAtras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(188, 188, 188)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reiniciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(introducirLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(255, 255, 255))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GenerarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GenerarISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(243, 243, 243)))
                .addComponent(imagenCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GenerarCodigo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GenerarISBN))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(introducirLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(7, 7, 7)
                        .addComponent(reiniciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cargarImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagenCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public GregorianCalendar getFechaPublicacion() { // se consigue captar la fecha del spinner
        Date dia = (Date) fechaPublicacion.getValue();
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dia);
        return gc;
    }

    public void setjFechaPublicacion(Date d) {
        this.fechaPublicacion.setValue(d);
    }
    public void camposEnBlanco() { //para revisar que ningun campo se quede en blanco por futuros errores
        
    }
    
    private void IrAltaPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrAltaPublicacionesActionPerformed
        // TODO add your handling code here:
        AltaPublicaciones altaP = new AltaPublicaciones();
        altaP.setVisible(true);
        SerializarLibros.guardarDatos();
        this.dispose(); // crea una clase AltaPublicaciones, ademas guarda el array con los datos de los libros
    }//GEN-LAST:event_IrAltaPublicacionesActionPerformed

    private void IrGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrGestionSociosActionPerformed
        // TODO add your handling code here:
        GestionAplicaciones ges1 = new GestionAplicaciones();
        ges1.setVisible(true);
        SerializarLibros.guardarDatos();
        this.dispose();//crea una clase GestionAplicaciones, ademas guarda el array con los datos de los libros
    }//GEN-LAST:event_IrGestionSociosActionPerformed

    private void IrMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuPrincipalActionPerformed
        // TODO add your handling code here:
        Biblioteca library = new Biblioteca();
        library.setVisible(true);
        SerializarLibros.guardarDatos();
        this.dispose();// crea una clase Biblioteca,y guarda el array con los datos de los libros
    }//GEN-LAST:event_IrMenuPrincipalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);  
        SerializarLibros.cargarDatos();//carga los datos de los libros, para actulizar el array que los lleva
    }//GEN-LAST:event_formWindowOpened

    private void autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoresActionPerformed

    private void materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaActionPerformed

    private void reiniciarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarDatosActionPerformed
            // Pone en blanco todos los campos de texto. Ademas  pone en su estado inicial al spinner de la fecha y al combobox
        codigo.setText("");
        ISBN.setText("");
        titulo.setText("");
        autores.setText("");
        paginas.setText("");
        materia.setText("");
        observaciones.setText("");
        ubicacion.setText("");
        GregorianCalendar gc = new GregorianCalendar();
        gc=(GregorianCalendar) Calendar.getInstance();
        Date dia = gc.getTime();
        fechaPublicacion.setValue(dia);
        resumen.setText("");
        localidad.setText("");
        editorial.setText("");
        edicion.setText("");
        imagenCaratula.setIcon(null);
        coleccion.setSelectedIndex(0);
    }//GEN-LAST:event_reiniciarDatosActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // TODO add your handling code here:
        String aux="C:\\Users\\Alvaro\\Documents\\NetBeansProjects\\PracticaFinal\\"; 
        //cadena que sirve para hacer la diferencia entre imagenes del proyecto y imagenes fuera de la carpeta
        String aux2;
        int ultimo;
        JFileChooser fc = new JFileChooser();//crea un selector de ficheros
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 
            /** si el valor del returnVal es el mismo que el que te da la opcion de "Aceptar" del selector
             entonces  se mete en codigo siguiente*/
            File file = fc.getSelectedFile(); //se consigue el archivo que se ha seleccionado
                path = file.getAbsolutePath(); //se consigue la ruta de acceso a ese archivo
                ultimo=path.length();//se consigue la longitud de esa cadena String
                if (ultimo>56){
                    /** lo que se va hacer a continuacion es diferenciar entre 
                     * las imagenes que se meten desde 
                     la carpeta del proyecto, y las que se meten desde fuera, 
                     * las que se meten desde una carpeta interna
                     del proyecto seran fijas, y las que se meten desde una carpeta
                     ajena no se veran si se cambia de ordenador, pero garantiza,
                     que al trasladar el programa funcione el cargador de imagenes*/
                    aux2=path.substring(0, 57);
                    if (aux2.equals(aux)){ // el codigo siguiente se hara si se mete desde la carpeta del proyecto
                         auxPath=path.substring(57,ultimo);
                        ImageIcon imagenes= new ImageIcon(auxPath);
                        imagenCaratula.setIcon(imagenes);
                        fuera=1;
                    }
                }
                else{// si la imagen es cargada desde una carpeta ajena del poryecto
                    ImageIcon imagenes= new ImageIcon(path);
                    imagenCaratula.setIcon(imagenes);
                    fuera=0;
                }
                
              
        } else {
            fc.setEnabled(false);
        }
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void introducirLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirLibroActionPerformed
        // TODO add your handling code here:
        String imagenC;
        //se van a conseguir los datos que son introducidos del libro desde el JFRAME
        try{
             String CodigoControl= codigo.getText();
             String isbn= ISBN.getText();
             String title= titulo.getText();
             String pag=paginas.getText();
             int pagi= Integer.parseInt(pag);
             String mater= materia.getText();
             String collection= (String) coleccion.getSelectedItem();
             String obser= observaciones.getText();
             String edito= editorial.getText();
             String edi= edicion.getText();
             String place= localidad.getText();
             String fisica= ubicacion.getText();
             String summary= resumen.getText();
             String author= autores.getText();
             if (fuera==1){ //si fuera =1 signficia que la iamgen esta en una carpeta internta del proyecto y se ejecuta este codigo
                imagenC=auxPath; //direccion de la imagen cuando esta en la carpeta proyecto
             }
             else {// si fuera =0, significa que la imagen es de una carpeta de fuera del proyecto
                imagenC=path;//direccion de la imagen cuando esta fuera de la carpeta proyecto
             }
                GregorianCalendar fecha=getFechaPublicacion();//se consigue la fecha del Spinner
             if (path.equals("") && auxPath.equals("")){//esto se hace para asegurarse de que se inserta una imagen
                   
              } else {
            /**  Ahora se va a instanciar la clase Libro, y se creara un objeto libro "Book
             que contendra los datos que hemos introducido, despues se introduciran en un arraylist
             de tipo Libros que serializaremos*/
             book =new Libros(edito,place,summary,edi,fisica,CodigoControl,isbn,title,author,fecha,imagenC,pagi,collection,mater,obser);
             boolean alta=SerializarLibros.altaLibro(book);
             if (alta==true) {
                JOptionPane.showMessageDialog(this, "Libro dado de alta.", "Mensaje de Alta", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
             }
            }
     }catch (NumberFormatException | HeadlessException e) {
       JOptionPane.showMessageDialog(this, "Campos sin rellenar o formato equivocado", "Mensaje de error", JOptionPane.ERROR_MESSAGE); 
       JOptionPane.showMessageDialog(this,"Si no ha insertado ninguna imagen, por favor insertela;"
                    + "\n"+ "Si no tiene ninguna imagen a  insertar puede usar una"
                    + " estandar que tiene la carpeta del programa" +"\n"
                    + "(la imagen se llama 'NoCaratula.PNG')"
                    ,"Mensaje de error",JOptionPane.WARNING_MESSAGE);    
    }//GEN-LAST:event_introducirLibroActionPerformed

    }
        private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
            SerializarLibros.guardarDatos();/**guarda el arraylist de libros que 
            *que hemos serializado */
    }//GEN-LAST:event_formWindowClosing

    private void GenerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarCodigoActionPerformed
        /** Sirve para generar el codigo ISBN y el codigo Control de los libros
         despues de generar se hace un repaso a todos los codigos del array list
         para asegurarse de que no hay codigos repetidos entre libros
         (aunque puede existir una revista y un libro con el mismo codigo)*/
       int codigoPubli; 
       String auxcodi;
       String codigoLib = null;
       Random rand=new Random();
  
       auxlibros=SerializarLibros.getLibros();
       li = auxlibros.listIterator(); // esto se hace cuando no hay datos en el array list 
            codigoPubli=rand.nextInt(10000);
            codigoPubli=codigoPubli+1000000;
            codigoLib=Integer.toString(codigoPubli);
            codigo.setText(codigoLib);
            
        if (auxlibros.size() >= 0) { //esto se hace cuando HAY datos en el arraylist
             while (li.hasNext()) {//que es cuando sed verifica que los codigos no sean iguales
                book = (Libros) li.next();  
                if (book != null) {
                     auxcodi=book.getCodigoControl();
                     if (auxcodi.equals(codigoLib)){
                         codigoPubli=rand.nextInt(10000);
                         codigoPubli=codigoPubli+1000000;
                         codigoLib=Integer.toString(codigoPubli);
                         codigo.setText(codigoLib);
                     } 
                }
             }
        }     
     
            
        
    }//GEN-LAST:event_GenerarCodigoActionPerformed

    private void GenerarISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarISBNActionPerformed
        
       int codigoPubli;// el codigo es el mismo que el de arriba, cambiando que al final se genera un ISBN
       String auxcodi;
       String codigoLib = null;
       Random rand=new Random();
       
       auxlibros=SerializarLibros.getLibros();
       li = auxlibros.listIterator();
            codigoPubli=rand.nextInt(10000);
            codigoPubli=codigoPubli+1000000;
            codigoLib=Integer.toString(codigoPubli);
            ISBN.setText(codigoLib);
            
        if (auxlibros.size() >= 0) {
             while (li.hasNext()) {
                book = (Libros) li.next();  
                if (book != null) {
                     auxcodi=book.getCodigoControl();
                     if (auxcodi.equals(codigoLib)){
                         codigoPubli=rand.nextInt(10000);
                         codigoPubli=codigoPubli+1000000;
                         codigoLib=Integer.toString(codigoPubli);
                         ISBN.setText(codigoLib);
                     } 
                }
            }
        }     
     
            
        
    }//GEN-LAST:event_GenerarISBNActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AltaLibros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarCodigo;
    private javax.swing.JButton GenerarISBN;
    private javax.swing.JTextField ISBN;
    private javax.swing.JRadioButtonMenuItem IrAltaPublicaciones;
    private javax.swing.JRadioButtonMenuItem IrGestionSocios;
    private javax.swing.JRadioButtonMenuItem IrMenuPrincipal;
    private javax.swing.JTextField autores;
    private javax.swing.JButton cargarImagen;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox coleccion;
    private javax.swing.JTextField edicion;
    private javax.swing.JTextField editorial;
    private javax.swing.JSpinner fechaPublicacion;
    private javax.swing.JLabel imagenCaratula;
    private javax.swing.JButton introducirLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField materia;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JMenu opcionAtras;
    private javax.swing.JTextField paginas;
    private javax.swing.JButton reiniciarDatos;
    private javax.swing.JTextArea resumen;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField ubicacion;
    // End of variables declaration//GEN-END:variables
}
