/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

import Clases.Libros;
import Clases.SerializarLibros;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.ListIterator;
import javax.swing.*;

/**
 *
 * @author Alvaro
 */
public class ConsultaModificacionLibros extends javax.swing.JFrame {
      public Libros book= null;
      public static ArrayList<Libros> auxlibros = new ArrayList<Libros>();
      public ListIterator li;
      String path,auxPath;
      String imagenC;
      boolean nuevaImagen;
      public int fuera=2;
    
    /**
     * Creates new form ConsultaModificacionLibros
     */
    public ConsultaModificacionLibros() {
        initComponents();
        this.setTitle("Biblioteca de la UAH");
    }
     public GregorianCalendar getFechaPublicacion() { //metodo para coger la fecha de publicacion
        Date dia = (Date) fechaPublicacion.getValue();
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dia);
        return gc;
    }

    public void setjFechaPublicacion(Date d) {
        this.fechaPublicacion.setValue(d);
    }
    
    private void mostrarDatos(Libros book) { //metodo para mostrar los datos en la ventana del libro
                codigo.setText(book.getCodigoControl());
                ISBN.setText(book.getISBN());
                titulo.setText(book.getTitulo());
                autores.setText(book.getAutores());
                materia.setText(book.getGenero());
                observaciones.setText(book.getObservaciones());
                editorial.setText(book.getEditorial());
                edicion.setText(book.getEdicion());
                localidad.setText(book.getLocalidad());
                ubicacion.setText(book.getLocalizacionFisica());
                resumen.setText(book.getContenido());
   
                int auxpag=book.getPaginas();
                String auxpag2= Integer.toString(auxpag);
                paginas.setText(auxpag2);
                
                String collection=book.getColeccion();
                    if (collection.equals("SI")) {
                        coleccion.setSelectedIndex(0);
                    }
                    if (collection.equals("NO")) {
                        coleccion.setSelectedIndex(1);
                    }
                
               imagenC=book.getCaratula();
               ImageIcon imagenes=new ImageIcon(imagenC);
               imagenCaratula.setIcon(imagenes);
               
               GregorianCalendar daux= book.getFechaPublicacion();
               Date daux2= daux.getTime();
               fechaPublicacion.setValue(daux2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        autores = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaPublicacion = new javax.swing.JSpinner();
        paginas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        coleccion = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        materia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        editorial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edicion = new javax.swing.JTextField();
        localidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ubicacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        modificarLibro = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        imagenFrente = new javax.swing.JLabel();
        imagenCaratula = new javax.swing.JLabel();
        cargarImagen = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        borrarLibro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionAtras = new javax.swing.JMenu();
        IrGestionSocios = new javax.swing.JRadioButtonMenuItem();
        IrMenuPrincipal = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBiblio.png"))); // NOI18N

        codigo.setEditable(false);

        jLabel1.setText("código");

        jLabel2.setText("ISBN");

        ISBN.setEditable(false);

        titulo.setEditable(false);

        jLabel3.setText("Título");

        jLabel4.setText("Autores");

        autores.setEditable(false);
        autores.setToolTipText("");
        autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoresActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de Publicación");

        fechaPublicacion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-11676099600000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        fechaPublicacion.setToolTipText("haz \"doble click\" en el dato de la fecha que quieras cambiar");
        fechaPublicacion.setEditor(new javax.swing.JSpinner.DateEditor(fechaPublicacion, "dd/MM/yyyy"));
        fechaPublicacion.setEnabled(false);

        paginas.setEditable(false);

        jLabel7.setText("Páginas");

        coleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        coleccion.setEnabled(false);

        jLabel8.setText("con Colección");

        jLabel9.setText("Materia");

        materia.setEditable(false);
        materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaActionPerformed(evt);
            }
        });

        jLabel10.setText("Observaciones");

        observaciones.setColumns(20);
        observaciones.setEditable(false);
        observaciones.setRows(5);
        jScrollPane2.setViewportView(observaciones);

        editorial.setEditable(false);

        jLabel11.setText("Editorial");

        jLabel13.setText("Edición");

        edicion.setEditable(false);

        localidad.setEditable(false);

        jLabel12.setText("Localidad");

        jLabel14.setText("Ubicación en la Biblioteca");
        jLabel14.setRequestFocusEnabled(false);

        ubicacion.setEditable(false);

        resumen.setColumns(20);
        resumen.setEditable(false);
        resumen.setRows(5);
        jScrollPane1.setViewportView(resumen);

        jLabel16.setText("Resumen");

        jLabel17.setText("Carátula");

        modificarLibro.setBackground(new java.awt.Color(255, 153, 0));
        modificarLibro.setText("MODIFICAR LIBRO");
        modificarLibro.setToolTipText("Modifica los valores del libro actual");
        modificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarLibroActionPerformed(evt);
            }
        });

        guardarCambios.setBackground(new java.awt.Color(51, 255, 51));
        guardarCambios.setText("GUARDAR CAMBIOS");
        guardarCambios.setToolTipText("guarda los cambios del libro actual");
        guardarCambios.setEnabled(false);
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoSiguiente.png"))); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 204)));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        cargarImagen.setText("Cargar imagen");
        cargarImagen.setEnabled(false);
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });

        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoAnterior.png"))); // NOI18N
        anterior.setText("Anterior");
        anterior.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 0)));
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        borrarLibro.setBackground(new java.awt.Color(255, 0, 0));
        borrarLibro.setText("BORRAR LIBRO");
        borrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarLibroActionPerformed(evt);
            }
        });

        opcionAtras.setText("ATRAS");

        IrGestionSocios.setSelected(true);
        IrGestionSocios.setText("Gestion Publicaciones");
        IrGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrGestionSociosActionPerformed(evt);
            }
        });
        opcionAtras.add(IrGestionSocios);

        IrMenuPrincipal.setSelected(true);
        IrMenuPrincipal.setText("Menu Principal");
        IrMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuPrincipalActionPerformed(evt);
            }
        });
        opcionAtras.add(IrMenuPrincipal);

        jMenuBar1.add(opcionAtras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(368, 368, 368))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(3, 3, 3)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(edicion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(borrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(149, 149, 149)
                                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(80, 80, 80)
                                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(imagenCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(imagenFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(434, 434, 434))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modificarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargarImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagenFrente, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(imagenCaratula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null); // centra la ventana en la pantalla
        SerializarLibros.cargarDatos();//carga el array de tipo Libros con los datos de estos
        try{
            auxlibros=SerializarLibros.getLibros();
            li = auxlibros.listIterator();
        
            if (auxlibros.size() < 1) { // si el tamaño es menor que 1, significa que no hay libros
                JOptionPane.showMessageDialog(this, "No hay libros.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
             }
            if (li.hasNext()) {
                book = (Libros) li.next();//se obtiene el primer libro
            
                if (book != null) {
                 mostrarDatos(book);//se muestra los datos del primer libro
                 }
             }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void IrGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrGestionSociosActionPerformed
        // TODO add your handling code here:
        GestionAplicaciones Ges1 = new GestionAplicaciones();
        Ges1.setVisible(true);
        SerializarLibros.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrGestionSociosActionPerformed

    private void IrMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuPrincipalActionPerformed
        // TODO add your handling code here:
        Biblioteca library = new Biblioteca();
        library.setVisible(true);
        SerializarLibros.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrMenuPrincipalActionPerformed

    private void autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoresActionPerformed

    private void materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaActionPerformed

    private void modificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarLibroActionPerformed
        // Activa todos los campos de texto, para que se puedan modificar
        //tambien activa el boton de guardar y cargar imagenes
         JOptionPane.showMessageDialog(this,"Ahora se pueden modificar los campos "
                    + " del libro ","Mensaje de Modificación",JOptionPane.INFORMATION_MESSAGE);
        codigo.setEditable(true);
        ISBN.setEditable(true);
        titulo.setEditable(true);
        autores.setEditable(true);
        paginas.setEditable(true);
        materia.setEditable(true);
        observaciones.setEditable(true);
        coleccion.setEnabled(true);
        fechaPublicacion.setEnabled(true);
        editorial.setEditable(true);
        edicion.setEditable(true);
        localidad.setEditable(true);
        ubicacion.setEditable(true);
        resumen.setEditable(true);
        cargarImagen.setEnabled(true);
        guardarCambios.setEnabled(true);
    }//GEN-LAST:event_modificarLibroActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        
         try{
            if (li.hasNext()) {
               book = (Libros) li.next();//se obtiene el libro siguiente
               if (book != null) {
                    mostrarDatos(book);// si hay datos en ese objeto libro se muestran en la pantalla
               }  
           } else {
              JOptionPane.showMessageDialog(this, "No hay mas libros.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // Es el mismo metodo que el descrito en AltaLibros.java
        String aux="C:\\Users\\Alvaro\\Documents\\NetBeansProjects\\PracticaFinal\\";
        String aux2;
        int ultimo;
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
                path = file.getAbsolutePath();
                ultimo=path.length();
                if (ultimo>56){
                aux2=path.substring(0, 57);
                if (aux2.equals(aux)){
                     auxPath=path.substring(57,ultimo);
                     ImageIcon imagenes = new ImageIcon(auxPath);
                     imagenCaratula.setIcon(imagenes);
                     fuera=1;
                }
                }
                else{
                    ImageIcon imagenes= new ImageIcon(path);
                    imagenCaratula.setIcon(imagenes);
                    fuera=0;
                }
                
              
        } else {
            fc.setEnabled(false);
        }
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        try{
            if (li.hasPrevious()) { 
                book = (Libros) li.previous();//se obtiene el libro anterior del actual
                if (book != null) { // si el libro anterior tiene datos se llama al metodo y se muestran los datos
                    mostrarDatos(book);
               }  
           } else {
                JOptionPane.showMessageDialog(this, "No hay mas libros.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
        
        
    }//GEN-LAST:event_anteriorActionPerformed

    private void borrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarLibroActionPerformed
        // El sigueinte codigo borra el libro que se este mostrando actualmente
         int n = 0;
         n = JOptionPane.showConfirmDialog( //se crea un mensaje de confirmacion, si la opcion es "SI" se procede a borrarlo
                    this, "Desea borrar el libro?",
                    "Diálogo de Confirmación",
                    JOptionPane.YES_NO_CANCEL_OPTION);
         if (n == JOptionPane.YES_OPTION) { 
            if (book != null) { // si el libro no esta vacio, es decir, hay datos
                li.remove();//se borra el libro que se mostrando actualemtente
                JOptionPane.showMessageDialog(this, "Libro borrado de la Biblioteca","Mensaje de baja", JOptionPane.WARNING_MESSAGE);
            }
            if (li.hasNext()) { // si se ha borrado el libro, la ventana te lleva al siguiente libro (para no quedar en blanco o parado la ventana
                book = (Libros) li.next();
                if (book != null) {
                    mostrarDatos(book);// muestra los datos del siguiente libro
                } else { // si no hay mas libros se muestra el siguiente mensaje
                JOptionPane.showMessageDialog(this, "No hay Libros", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (li.hasPrevious()) { // si no tiene mas libros delante suyo, muestra sus anteriores
                 book = (Libros) li.previous();
                if (book != null) {
                    mostrarDatos(book);// muestra los datos del libro anterior
                } else {
                    JOptionPane.showMessageDialog(this, "No hay Libros.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            }    
        } else if (n == JOptionPane.NO_OPTION) {
         
        }else if (n == JOptionPane.CANCEL_OPTION){
        
        }
        SerializarLibros.guardarDatos();// se guardan los cambios
        ConsultaModificacionLibros cambios= new ConsultaModificacionLibros();
        cambios.setVisible(true);
        this.dispose(); 
        //se crea una nueva ventana y se cierra esta para que se vean los cambios
      
    }//GEN-LAST:event_borrarLibroActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        // Se obtienen los datos de todos los campos de libro
            
        try{
            li.remove();//se borra el actual libro, para no hacer duplicaciones
            String CodigoControl= codigo.getText();
            String isbn= ISBN.getText();
            String title= titulo.getText();
            String pag=paginas.getText();
            int pagi= Integer.parseInt(pag);
            String mater= materia.getText();
            String collection= (String) coleccion.getSelectedItem();
            String obser= observaciones.getText();
            String edito= editorial.getText();
            String edi= edicion.getText();
            String place= localidad.getText();
            String fisica= ubicacion.getText();
            String summary= resumen.getText();
            String author= autores.getText();
            if (fuera==1){ //si fuera =1 signficia que la iamgen esta en una carpeta internta del proyecto y se ejecuta este codigo
                    imagenC=auxPath; //direccion de la imagen cuando esta en la carpeta proyecto
            }
            if (fuera==0){// si fuera =0, significa que la imagen es de una carpeta de fuera del proyecto
                    imagenC=path;//direccion de la imagen cuando esta fuera de la carpeta proyecto
             }
             
             GregorianCalendar fecha=getFechaPublicacion();
             book =new Libros(edito,place,summary,edi,fisica,CodigoControl,isbn,title,author,fecha,imagenC,pagi,collection,mater,obser);
             boolean alta=SerializarLibros.altaLibro(book);
             //se instancia el nuevo libro y se guarda en el array list de tipo Libro
             if (alta==true) {
                JOptionPane.showMessageDialog(this, "Cambios guardados.", "Mensaje de Alta", JOptionPane.INFORMATION_MESSAGE);
                SerializarLibros.guardarDatos();
                ConsultaModificacionLibros cambios= new ConsultaModificacionLibros();
                cambios.setVisible(true);
                this.dispose();
             } else {
                JOptionPane.showMessageDialog(this, "Error al guardar.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this,"Asegurese de que todos los campos estan rellenos"
                + " o los formatos estan correctos","Mensaje informativo",JOptionPane.INFORMATION_MESSAGE);
            }
    }catch (Exception e) {
          
        JOptionPane.showMessageDialog(this, "Excepción al Guardar.", "Mensaje de error", JOptionPane.ERROR_MESSAGE); 
        JOptionPane.showMessageDialog(this,"Ha habido una excepcion al guardar"+"\n"+
                "Formato en campos no correctos"+"\n"+"se han restablecido los valores iniciales","Mensaje de informacion",
        JOptionPane.INFORMATION_MESSAGE);
        li.add(book);// si da error al guardar, se guarda otra vez los datos del libro actual
        ConsultaModificacionLibros cambios= new ConsultaModificacionLibros();
        cambios.setVisible(true);
        this.dispose();   // se cierra la actual ventana y se abre una misma para que se vean antes los NO cambios.
        
    }  
     
       
       //abre una nueva ventana para que sea inmente los cambios producidos en el libro
    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        SerializarLibros.guardarDatos();//guarda el arrayList de tipo Libro
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaModificacionLibros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBN;
    private javax.swing.JRadioButtonMenuItem IrGestionSocios;
    private javax.swing.JRadioButtonMenuItem IrMenuPrincipal;
    private javax.swing.JButton anterior;
    private javax.swing.JTextField autores;
    private javax.swing.JButton borrarLibro;
    private javax.swing.JButton cargarImagen;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox coleccion;
    private javax.swing.JTextField edicion;
    private javax.swing.JTextField editorial;
    private javax.swing.JSpinner fechaPublicacion;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel imagenCaratula;
    private javax.swing.JLabel imagenFrente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField materia;
    private javax.swing.JButton modificarLibro;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JMenu opcionAtras;
    private javax.swing.JTextField paginas;
    private javax.swing.JTextArea resumen;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField ubicacion;
    // End of variables declaration//GEN-END:variables
}
