/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

import Clases.Revistas;
import Clases.SerializarRevistas;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.ListIterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class ConsultaModificacionRevistas extends javax.swing.JFrame {
      public Revistas magazine= null;
      public static ArrayList<Revistas> auxRevistas = new ArrayList<Revistas>();
      public ListIterator li;
      String path,auxPath;
      String imagenC;
      boolean nuevaImagen;
      int fuera=2;
     
 public GregorianCalendar getFechaPublicacion() {
        Date dia = (Date) fechaPublicacion.getValue();
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dia);
        return gc;
    }
 public GregorianCalendar getFechaDisponible() {
        Date dia2 = (Date) anioDisponible.getValue();
        GregorianCalendar gc2 = new GregorianCalendar();
        gc2.setTime(dia2);
        return gc2;
 }
    /**
     * Creates new form ConsultaModificacionRevistas
     */
    public ConsultaModificacionRevistas() {
        initComponents();
        this.setTitle("Biblioteca de la UAH");
    }
    private void mostrarDatos(Revistas magazine) {
           codigo.setText(magazine.getCodigoControl());
           ISBN.setText(magazine.getISBN());
           titulo.setText(magazine.getTitulo());
           autores.setText(magazine.getAutores());
           ubicacion.setText(magazine.getLocalizacionFisica());
           materia.setText(magazine.getGenero());
           observaciones.setText(magazine.getObservaciones());
           periocidad.setText(magazine.getPeriocidad());      
           String collection=magazine.getColeccion();
               if (collection.equals("SI")) {
                    coleccion.setSelectedIndex(0);
               }
               if (collection.equals("NO")) {
                    coleccion.setSelectedIndex(1);
               }
          imagenC=magazine.getCaratula();
          ImageIcon imagenes=new ImageIcon(imagenC);
          imagenCaratula.setIcon(imagenes);               
          int auxpag=magazine.getPaginas();
          String auxpag2= Integer.toString(auxpag);
          paginas.setText(auxpag2);         
          int auxvol=magazine.getVolumen();
          String vol=Integer.toString(auxvol);
          volumen.setText(vol);       
          int auxnum=magazine.getNumero();
          String number=Integer.toString(auxnum);
          numeroRevista.setText(number);      
           GregorianCalendar daux= magazine.getFechaPublicacion();
           Date daux2= daux.getTime();
           fechaPublicacion.setValue(daux2);
               
          GregorianCalendar daux3= magazine.getAnioDisponible();
          Date daux4= daux3.getTime();
          anioDisponible.setValue(daux4);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        modificarRevista = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        coleccion = new javax.swing.JComboBox();
        paginas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaPublicacion = new javax.swing.JSpinner();
        autores = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        ISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ubicacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        anioDisponible = new javax.swing.JSpinner();
        numeroRevista = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        volumen = new javax.swing.JTextField();
        periocidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        materia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();
        imagenCaratula = new javax.swing.JLabel();
        cargarImagen = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        borrarLibro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionAtras = new javax.swing.JMenu();
        IrGestionSocios = new javax.swing.JRadioButtonMenuItem();
        IrMenuPrincipal = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBiblio.png"))); // NOI18N

        modificarRevista.setBackground(new java.awt.Color(255, 153, 0));
        modificarRevista.setText("MODIFICAR REVISTA");
        modificarRevista.setToolTipText("Modifica los datos de la revista actual");
        modificarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarRevistaActionPerformed(evt);
            }
        });

        guardarCambios.setBackground(new java.awt.Color(51, 255, 51));
        guardarCambios.setText("GUARDAR CAMBIOS");
        guardarCambios.setToolTipText("Guarda los cambios actuales ");
        guardarCambios.setEnabled(false);
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        jLabel8.setText("con Colección");

        coleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        coleccion.setEnabled(false);

        paginas.setEditable(false);

        jLabel7.setText("Páginas");

        jLabel6.setText("Fecha de Publicación");

        fechaPublicacion.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-11676099600000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        fechaPublicacion.setToolTipText("haz \"doble click\" en el dato de la fecha que quieras cambiar");
        fechaPublicacion.setEditor(new javax.swing.JSpinner.DateEditor(fechaPublicacion, "dd/MM/yyyy"));
        fechaPublicacion.setEnabled(false);

        autores.setEditable(false);
        autores.setToolTipText("");

        jLabel4.setText("Autores");

        jLabel3.setText("Título");

        titulo.setEditable(false);

        ISBN.setEditable(false);

        jLabel2.setText("ISBN");

        jLabel1.setText("código");

        codigo.setEditable(false);

        jLabel16.setText("Ubicación en la Biblioteca");

        ubicacion.setEditable(false);
        ubicacion.setAutoscrolls(false);
        ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionActionPerformed(evt);
            }
        });

        jLabel14.setText("Año Disponible");

        anioDisponible.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-11676099600000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        anioDisponible.setToolTipText("haz \"doble click\" en el dato de la fecha que quieras cambiar");
        anioDisponible.setEditor(new javax.swing.JSpinner.DateEditor(anioDisponible, "dd/MM/yyyy"));
        anioDisponible.setEnabled(false);

        numeroRevista.setEditable(false);

        jLabel13.setText("Numero");

        jLabel12.setText("Volumen");

        volumen.setEditable(false);

        periocidad.setEditable(false);

        jLabel11.setText("Periocidad");

        jLabel10.setText("Observaciones");

        observaciones.setColumns(20);
        observaciones.setEditable(false);
        observaciones.setRows(5);
        observaciones.setText("\n");
        jScrollPane1.setViewportView(observaciones);

        materia.setEditable(false);

        jLabel9.setText("Materia");

        jLabel15.setText("Caráctula");

        siguiente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alvaro\\Documents\\NetBeansProjects\\PracticaFinal\\src\\Imagenes\\IconoSiguiente.png")); // NOI18N
        siguiente.setText("Siguiente");
        siguiente.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 204)));
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        cargarImagen.setText("Cargar imagen");
        cargarImagen.setEnabled(false);
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });

        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoAnterior.png"))); // NOI18N
        anterior.setText("Anterior");
        anterior.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 0)));
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        borrarLibro.setBackground(new java.awt.Color(255, 0, 0));
        borrarLibro.setText("BORRAR REVISTA");
        borrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarLibroActionPerformed(evt);
            }
        });

        opcionAtras.setText("ATRAS");

        IrGestionSocios.setSelected(true);
        IrGestionSocios.setText("Gestion Publicaciones");
        IrGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrGestionSociosActionPerformed(evt);
            }
        });
        opcionAtras.add(IrGestionSocios);

        IrMenuPrincipal.setSelected(true);
        IrMenuPrincipal.setText("Menu Principal");
        IrMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuPrincipalActionPerformed(evt);
            }
        });
        opcionAtras.add(IrMenuPrincipal);

        jMenuBar1.add(opcionAtras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(ubicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addGap(268, 268, 268))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(periocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numeroRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(anioDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addComponent(imagenCaratula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 545, Short.MAX_VALUE)
                .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modificarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(borrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(paginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(coleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(periocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(numeroRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(anioDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargarImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagenCaratula, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IrGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrGestionSociosActionPerformed
        // TODO add your handling code here:
        GestionAplicaciones Ges1 = new GestionAplicaciones();
        Ges1.setVisible(true);
        SerializarRevistas.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrGestionSociosActionPerformed

    private void IrMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuPrincipalActionPerformed
        // TODO add your handling code here:
        Biblioteca library = new Biblioteca();
        library.setVisible(true);
        SerializarRevistas.guardarDatos();
        this.dispose();
    }//GEN-LAST:event_IrMenuPrincipalActionPerformed

    private void modificarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarRevistaActionPerformed
        // Activa todos los campos de texto para que se puedan modificar
        //tambien activa el boton de guardar y cargar imagenes
        JOptionPane.showMessageDialog(this,"Ahora se pueden modificar los campos "
                    + " de la revitsa ","Mensaje de Modificación",JOptionPane.INFORMATION_MESSAGE);
        codigo.setEditable(true);
        ISBN.setEditable(true);
        titulo.setEditable(true);
        autores.setEditable(true);
        paginas.setEditable(true);
        materia.setEditable(true);
        observaciones.setEditable(true);
        coleccion.setEnabled(true);
        fechaPublicacion.setEnabled(true);
        periocidad.setEditable(true);
        volumen.setEditable(true);
        numeroRevista.setEditable(true);
        ubicacion.setEditable(true);
        anioDisponible.setEnabled(true);
        cargarImagen.setEnabled(true);
        guardarCambios.setEnabled(true);
    }//GEN-LAST:event_modificarRevistaActionPerformed

    private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setLocationRelativeTo(null);
        SerializarRevistas.cargarDatos();
        try{
        auxRevistas=SerializarRevistas.getRevista();
        li = auxRevistas.listIterator();
        
        if (auxRevistas.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay Revistas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        if (li.hasNext()) {
                magazine = (Revistas) li.next();
            
             if (magazine != null) {
                 mostrarDatos(magazine);
             }
        }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }//GEN-LAST:event_formWindowOpened

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
         try{
        if (li.hasNext()) {
                magazine = (Revistas) li.next();
            
        if (magazine != null) {
                 mostrarDatos(magazine);
               }  
           } else {
                JOptionPane.showMessageDialog(this, "No hay mas Revistas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
        
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // TODO add your handling code here:
        String aux="C:\\Users\\Alvaro\\Documents\\NetBeansProjects\\PracticaFinal\\";
        String aux2;
        int ultimo;
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
                path = file.getAbsolutePath();
                ultimo=path.length();
                if (ultimo>56){
                aux2=path.substring(0, 57);
                if (aux2.equals(aux)){
                     auxPath=path.substring(57,ultimo);
                     ImageIcon imagenes = new ImageIcon(auxPath);
                     imagenCaratula.setIcon(imagenes);
                     fuera=1;
                }
                }
                else{
                    ImageIcon imagenes= new ImageIcon(path);
                    imagenCaratula.setIcon(imagenes);
                    fuera=0;
                }
                
              
        } else {
            fc.setEnabled(false);
        }
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        // TODO add your handling code here:
        try{
             if (li.hasPrevious()) {
                magazine = (Revistas) li.previous();    
                if (magazine != null) {
                     mostrarDatos(magazine); 
               }  
           } else {
                JOptionPane.showMessageDialog(this, "No hay mas Revistas.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
            
        }
        
    }//GEN-LAST:event_anteriorActionPerformed

    private void borrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarLibroActionPerformed
        // TODO add your handling code here:
        int n = 0;
        n = JOptionPane.showConfirmDialog(
                    this, "Desea borrar la revista?",
                    "Diálogo de Confirmación",
                    JOptionPane.YES_NO_CANCEL_OPTION);
         if (n == JOptionPane.YES_OPTION) { 
            if (magazine != null) {
                li.remove();
                JOptionPane.showMessageDialog(this, "Revista borrada de la Biblioteca", "Mensaje de baja", JOptionPane.WARNING_MESSAGE);
            }
            if (li.hasNext()) {
                magazine = (Revistas) li.next();
                if (magazine != null) {
                    mostrarDatos(magazine);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay Revista", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            } else if (li.hasPrevious()) {
                magazine = (Revistas) li.previous();
                if (magazine != null) {
                    mostrarDatos(magazine);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay Revista.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        ConsultaModificacionRevistas cambios= new ConsultaModificacionRevistas();
        cambios.setVisible(true);
        SerializarRevistas.guardarDatos();
        this.dispose();
        }else if (n == JOptionPane.NO_OPTION) {
         
        }else if (n == JOptionPane.CANCEL_OPTION){
        
        }
      
    }//GEN-LAST:event_borrarLibroActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        // TODO add your handling code here:
        try{
            li.remove();
            String CodigoControl= codigo.getText();
            String isbn= ISBN.getText();
            String title= titulo.getText();
            String pag=paginas.getText();
            int pagi= Integer.parseInt(pag);
            String mater= materia.getText();
            String collection= (String) coleccion.getSelectedItem();
            String obser= observaciones.getText();
            String period= periocidad.getText();
            String vol= volumen.getText();
            int volR=Integer.parseInt(vol);
            String num= numeroRevista.getText();
            int number=Integer.parseInt(num);
            String fisica= ubicacion.getText();
            String author= autores.getText();
            if (fuera==1){ //si fuera =1 signficia que la iamgen esta en una carpeta internta del proyecto y se ejecuta este codigo
                imagenC=auxPath; //direccion de la imagen cuando esta en la carpeta proyecto
            }
            if (fuera==0) {// si fuera =0, significa que la imagen es de una carpeta de fuera del proyecto
                imagenC=path;//direccion de la imagen cuando esta fuera de la carpeta proyecto
            }
            GregorianCalendar fechaPubli=getFechaPublicacion();
            GregorianCalendar fechaDisponible=getFechaDisponible();
         
            magazine =new Revistas(period,volR,number,fechaDisponible,fisica,CodigoControl,isbn,title,author,fechaPubli,imagenC,pagi,collection,mater,obser);
            boolean alta=SerializarRevistas.altaRevista(magazine);
            if (alta==true) {
                JOptionPane.showMessageDialog(this, "Cambios guardados.", "Mensaje de Guardado", JOptionPane.INFORMATION_MESSAGE);
                SerializarRevistas.guardarDatos();
                 ConsultaModificacionRevistas cambios= new ConsultaModificacionRevistas();
                 cambios.setVisible(true);
                 this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this,"Asegurese de que todos los campos estan rellenos"
                + "o los formatos estan correctos","Mensaje informativo",JOptionPane.INFORMATION_MESSAGE);
            }
     }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Excepción al guardar.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);   
             JOptionPane.showMessageDialog(this,"Ha habido una excepcion al guradar"+"\n"+
                "Formato en campos no correctos"+"\n"+"se han restablecido los valores iniciales","Mensaje de informacion",
             JOptionPane.INFORMATION_MESSAGE);
            li.add(magazine);
            ConsultaModificacionRevistas cambios= new ConsultaModificacionRevistas();
             cambios.setVisible(true);
             this.dispose();  
     }
        
     
        
    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here
        SerializarRevistas.guardarDatos();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaModificacionRevistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConsultaModificacionRevistas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBN;
    private javax.swing.JRadioButtonMenuItem IrGestionSocios;
    private javax.swing.JRadioButtonMenuItem IrMenuPrincipal;
    private javax.swing.JSpinner anioDisponible;
    private javax.swing.JButton anterior;
    private javax.swing.JTextField autores;
    private javax.swing.JButton borrarLibro;
    private javax.swing.JButton cargarImagen;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox coleccion;
    private javax.swing.JSpinner fechaPublicacion;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel imagenCaratula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField materia;
    private javax.swing.JButton modificarRevista;
    private javax.swing.JTextField numeroRevista;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JMenu opcionAtras;
    private javax.swing.JTextField paginas;
    private javax.swing.JTextField periocidad;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField ubicacion;
    private javax.swing.JTextField volumen;
    // End of variables declaration//GEN-END:variables
}
