/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

/**
 *
 * @author Alvaro
 */
public class GestionAplicaciones extends javax.swing.JFrame {

    /**
     * Creates new form GestionAplicaciones
     */
    public GestionAplicaciones() {
        initComponents();
        this.setTitle("Biblioteca de la UAH");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionConMo = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        librosCo = new javax.swing.JButton();
        revistasCo = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        opcionAtras1 = new javax.swing.JMenu();
        IrGestionSocios = new javax.swing.JRadioButtonMenuItem();
        IrMenuPrincipal1 = new javax.swing.JRadioButtonMenuItem();
        jLabel5 = new javax.swing.JLabel();
        gestionPublicaciones = new javax.swing.JButton();
        altaPubli = new javax.swing.JButton();
        prestamoPubli = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcionAtras = new javax.swing.JMenu();
        IrMenuPrincipal = new javax.swing.JRadioButtonMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("¿Qué quiere Consultar/Modificar ?");

        librosCo.setBackground(new java.awt.Color(153, 255, 255));
        librosCo.setText("LIBROS");
        librosCo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        librosCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosCoActionPerformed(evt);
            }
        });

        revistasCo.setBackground(new java.awt.Color(255, 255, 51));
        revistasCo.setText("REVISTAS");
        revistasCo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        revistasCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revistasCoActionPerformed(evt);
            }
        });

        opcionAtras1.setText("ATRAS");

        IrGestionSocios.setSelected(true);
        IrGestionSocios.setText("Gestion Publicaciones");
        IrGestionSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrGestionSociosActionPerformed(evt);
            }
        });
        opcionAtras1.add(IrGestionSocios);

        IrMenuPrincipal1.setSelected(true);
        IrMenuPrincipal1.setText("Menu Principal");
        IrMenuPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuPrincipal1ActionPerformed(evt);
            }
        });
        opcionAtras1.add(IrMenuPrincipal1);

        jMenuBar2.add(opcionAtras1);

        opcionConMo.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout opcionConMoLayout = new javax.swing.GroupLayout(opcionConMo.getContentPane());
        opcionConMo.getContentPane().setLayout(opcionConMoLayout);
        opcionConMoLayout.setHorizontalGroup(
            opcionConMoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionConMoLayout.createSequentialGroup()
                .addGroup(opcionConMoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionConMoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(opcionConMoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(librosCo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(revistasCo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        opcionConMoLayout.setVerticalGroup(
            opcionConMoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionConMoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(opcionConMoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librosCo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revistasCo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBiblio.png"))); // NOI18N

        gestionPublicaciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gestionPublicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionlibros.png"))); // NOI18N
        gestionPublicaciones.setText("GESTIÓN DE PUBLICACIONES");
        gestionPublicaciones.setToolTipText("Consulta, modifica y borra publicaciones");
        gestionPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionPublicacionesActionPerformed(evt);
            }
        });

        altaPubli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        altaPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/altaPublicacines.gif"))); // NOI18N
        altaPubli.setText("ALTA PUBLICACIONES");
        altaPubli.setToolTipText("Introduce nuevos libros o nuevas revistas en la Biblioteca");
        altaPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPubliActionPerformed(evt);
            }
        });

        prestamoPubli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prestamoPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prestamoicono.png"))); // NOI18N
        prestamoPubli.setText("PRÉSTAMO");
        prestamoPubli.setToolTipText("Accede al sistema de prestamos de la Biblioteca ");
        prestamoPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamoPubliActionPerformed(evt);
            }
        });

        opcionAtras.setText("ATRAS");

        IrMenuPrincipal.setSelected(true);
        IrMenuPrincipal.setText("Menu Principal");
        IrMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuPrincipalActionPerformed(evt);
            }
        });
        opcionAtras.add(IrMenuPrincipal);

        jMenuBar1.add(opcionAtras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(altaPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(prestamoPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(gestionPublicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prestamoPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altaPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(gestionPublicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // centra la ventana en la pantalla
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void IrMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuPrincipalActionPerformed
        
        Biblioteca library = new Biblioteca();
        library.setVisible(true);
        this.dispose();
        //abre la ventana del menu principal y cierra esta
    }//GEN-LAST:event_IrMenuPrincipalActionPerformed

    private void altaPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPubliActionPerformed
        
        AltaPublicaciones altaP=new AltaPublicaciones();
        altaP.setVisible(true);
        this.dispose();
        //abre la ventana de alta publicaciones y cierra esta
    }//GEN-LAST:event_altaPubliActionPerformed

    private void gestionPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPublicacionesActionPerformed
        // Abre un JFRAME interno (opcionConMo) - que decide si se quiere gestionar revista o libros
        opcionConMo.setVisible(true);
        opcionConMo.setSize(500, 200);
        opcionConMo.setTitle("Biblioteca de la UAH");
        opcionConMo.setLocationRelativeTo(null);
        //centra este JFrame interno
    }//GEN-LAST:event_gestionPublicacionesActionPerformed

    private void librosCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosCoActionPerformed
        // abre la ventana de gestion de libros y cierra el Jframe interno
        ConsultaModificacionLibros CoMoLib = new ConsultaModificacionLibros();
        CoMoLib.setVisible(true);
        opcionConMo.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_librosCoActionPerformed

    private void revistasCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revistasCoActionPerformed
        // Abre la ventana de gestion de revistas y cierra el Jframe interno
        ConsultaModificacionRevistas CoMoRev= new ConsultaModificacionRevistas();
        CoMoRev.setVisible(true);
        opcionConMo.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_revistasCoActionPerformed

    private void IrGestionSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrGestionSociosActionPerformed
        // Abre la ventana de gestion de aplicaciones
       
    }//GEN-LAST:event_IrGestionSociosActionPerformed

    private void IrMenuPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuPrincipal1ActionPerformed
        // Abre la ventana del menu principal y cierra esta
        Biblioteca library = new Biblioteca();
        library.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IrMenuPrincipal1ActionPerformed

    private void prestamoPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamoPubliActionPerformed
        //Abre la ventana de gestion de prestamo y cierra esta
        PrestamoPublicaciones PrestaPub = new PrestamoPublicaciones();
        PrestaPub.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prestamoPubliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAplicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAplicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAplicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAplicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GestionAplicaciones().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem IrGestionSocios;
    private javax.swing.JRadioButtonMenuItem IrMenuPrincipal;
    private javax.swing.JRadioButtonMenuItem IrMenuPrincipal1;
    private javax.swing.JButton altaPubli;
    private javax.swing.JButton gestionPublicaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton librosCo;
    private javax.swing.JMenu opcionAtras;
    private javax.swing.JMenu opcionAtras1;
    private javax.swing.JFrame opcionConMo;
    private javax.swing.JButton prestamoPubli;
    private javax.swing.JButton revistasCo;
    // End of variables declaration//GEN-END:variables
}
